My first OTUS homework
ostsle2/OTUS_HW1 pull request #1
Opened 2022-04-13 14:38 UTC by ostsle2

Домашнее задание
ДЗ #1: Автотест со своими ожиданиями

Цель:
Реализовать на практике полученные знания, с использованием Actions и своих ожиданий.

Описание/Пошаговая инструкция выполнения домашнего задания:
Необходимо создать проект в Maven'e и реализовать:

Фабрику (WebDriverFactory), которая будет получать значение из окружения и запускать соответствующий браузер Браузеры: Chrome, Firefox, Opera
Реализовать подсветку элементов перед нажатием, после нажатия вернуть данные в исходное состояние
На главно странице Otus'a снизу найти список курсов(популярные курсы, специализации, рекомендации) и реализовать:
Метод фильтр по названию курса
Метод выбора курса, стартующего раньше всех/позже всех (при совпадении дат - выбрать любой) при помощи reduce
Реализовать движение мыши при помощи и выбор курса при помощи библиотеки Actions
Критерии оценки:
Максимальная оценка 10 баллов.

2 Балла за реализацию фабрики
2 балла за подсветку элементов, +2 балла за возврат страницы в исходное состояние
1 бал за реализацию фильтра, +1 бал за реализацию reduce'ра
2 балла за реализацию Actions и выбора цвета
1 бал за каждое вмешательство преподавателя для запуска/работы тестов
2 балла за не реализованное задание Сдача: Сдача происходит через git. Необходимо приложить инструкцию (вариант, написать в readme.md) по запуску.
Рекомендуем сдать до: 30.03.2022

2022-04-17 10:17 UTC, saint88 requested changes
В репозиторий попала папка target, которая здесь не нужна. Ее надо удалить и добавить в .gitignore.

2022-04-17 10:17 UTC, saint88 commented on src/test/java/OpenCoursesTest.java
> +public class OpenCoursesTest extends BaseTest {
Наследовать классы тестов от базового класса в junit считается плохой практикой. Если тебе нужно в каждом классе с тестами вызывать одни и те же фикстуры, то лучше написать класс раннер в junit 4 и использовать его через аннотацию @RunWith и в этом раннере уже делать настройки драйвера, его инжекцию в класс тестов через аннотацию скажем @Driver и там же закрывать этот драйвер и сессию браузера. В общем исправь пожалуйста.

2022-04-17 10:17 UTC, saint88 commented on src/test/java/pages/BasePage.java
> +public class BasePage {
А у нас есть в природе базовая страница? Точнее мы можем создать объект базовой страницы? Наверное нет. Мы можем создать объект страницы поиска, главной страницы отуса или объект страницы карточки курса, но базовой страницы объект создать не можем, точнее не существует просто страницы. Поэтому надо запретить создание объекта базовой страницы через модификатор abstract.

2022-04-17 10:17 UTC, saint88 commented on src/test/java/pages/BasePage.java
> +    public BasePage waitUntilPageIsLoaded(WebDriverWait wait, String urlPath) {
С этим вейтером не согласен. Селениум ждет автоматически на протяжении определенного таймаута пока страница не вернет определенный статус (статус done на событии loadPage). И получается мы автоматически ждем пока страница загрузится, потом вызываем вейт, который никогда ждать не будет, а просто проверить совпадение урла и сразу завершится. Обычно делают по другому: открывают страницу и потом проверяют, что на странице отображается какой-то элемент или заголовок, который однозначно идентифицирует данную страницу. Таким образом, если у тебя страница загрузилась и на странице ничего не отобразилось, то твой вейтер скажет, что все гуд, а если мы проверим наличие скажем заголовка на главной странице отуса, то как минимум мы проверим, что у нас верстка в каком-то виде отрисовалась. В общем тоже надо поправить.

2022-04-17 10:17 UTC, saint88 commented on src/test/java/pages/CoursePage.java
> +    public CoursePage openCoursePage() {
Метод open() общий для всех страниц и поэтому его нужно вынести на BasePage. Типизировать через дженерики (организовать паттерн проектирования "навигация") и передавать path страницы например через конструктор или аннотацию (лучше второй вариант).

2022-04-17 10:17 UTC, saint88 commented on src/test/java/pages/CoursePage.java
> +    public CoursePage clickCourseWithName(String courseName) throws InterruptedException {
А вот здесь у тебя какой метод сгенерирует вот это исключение? Может его надо убрать?

2022-04-27 12:29 UTC, ostsle2 commented
> В репозиторий попала папка target, которая здесь не нужна. Ее надо удалить и добавить в .gitignore.

вроде удалила target из репозитория и добавила в .gitignore.

2022-04-27 12:29 UTC, ostsle2 commented on src/test/java/pages/CoursePage.java
> +    public CoursePage clickCourseWithName(String courseName) throws InterruptedException {
убрала лишнее исключение

2022-04-27 12:30 UTC, ostsle2 commented on src/test/java/pages/CoursePage.java
> +    public CoursePage openCoursePage() {
сделала

2022-04-27 12:31 UTC, ostsle2 commented on src/test/java/pages/BasePage.java
> +    public BasePage waitUntilPageIsLoaded(WebDriverWait wait, String urlPath) {
убрала этот вейтер, заменила на проверку     public void checkTitle(String expectedValue) {
        String actualTitle = this.getPageTitle();
        Assertions.assertEquals(expectedValue, actualTitle);
    }

2022-04-27 12:31 UTC, ostsle2 commented on src/test/java/pages/BasePage.java
> +public class BasePage {
сделала BasePage abstract

2022-04-27 12:32 UTC, ostsle2 commented on src/test/java/OpenCoursesTest.java
> +public class OpenCoursesTest extends BaseTest {
сделала отдельный класс MyRunner

2022-05-18 16:41 UTC, merged